### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ajs124** [silkeh/alertmanager_matrix#1]
I'm trying to deploy this project, but it crashes like so:
```
alertmanager-matrix-start[1662372]: 2021/03/11 03:23:45 http: panic serving [::1]:37820: runtime error: invalid memory address or nil pointer dereference 
alertmanager-matrix-start[1662372]: goroutine 83 [running]:
alertmanager-matrix-start[1662372]: net/http.(*conn).serve.func1(0xc0000b6280)
alertmanager-matrix-start[1662372]:  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.8/share/go/src/net/http/server.go:1801 +0x147
alertmanager-matrix-start[1662372]: panic(0x8ba200, 0xc613a0)
alertmanager-matrix-start[1662372]:  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.8/share/go/src/runtime/panic.go:975 +0x47a
alertmanager-matrix-start[1662372]: main.handler(0x9d5c60, 0xc0003f6000, 0xc0004a8e00)
alertmanager-matrix-start[1662372]:  /build/source/alertmanager_matrix.go:17 +0x36
alertmanager-matrix-start[1662372]: net/http.HandlerFunc.ServeHTTP(0x964130, 0x9d5c60, 0xc0003f6000, 0xc0004a8e00)
alertmanager-matrix-start[1662372]:  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.8/share/go/src/net/http/server.go:2042 +0x44
alertmanager-matrix-start[1662372]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000a60c0, 0x9d5c60, 0xc0003f6000, 0xc0004a8a00)
alertmanager-matrix-start[1662372]:  /build/source/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
alertmanager-matrix-start[1662372]: net/http.serverHandler.ServeHTTP(0xc00016a0e0, 0x9d5c60, 0xc0003f6000, 0xc0004a8a00)
alertmanager-matrix-start[1662372]:  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.8/share/go/src/net/http/server.go:2843 +0xa3
alertmanager-matrix-start[1662372]: net/http.(*conn).serve(0xc0000b6280, 0x9d7060, 0xc0000c8280)
alertmanager-matrix-start[1662372]:  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.8/share/go/src/net/http/server.go:1925 +0x8ad
alertmanager-matrix-start[1662372]: created by net/http.(*Server).Serve
alertmanager-matrix-start[1662372]:  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.8/share/go/src/net/http/server.go:2969 +0x36c
```

Please ignore the `/nix/store` path prefixes.

I'm invoking it with the following parameters: 
```
  -alertmanager 'http://127.0.0.1:9093' \
  -homeserver http://my-homeserver \
  -userID '@a:my-homeserver' \
  -rooms '!id:my-homeserver'
```
and it did join the room, so that seems to be working. The token is set through an environment file.

The crash occurs when it's receiving an alert from alert manager.

**Comment by crozone** [comment]
@ajs124 We are also experiencing this error:

```
http: panic serving [::1]:44906: runtime error: invalid memory address or nil pointer dereference
goroutine 557 [running]:
net/http.(*conn).serve.func1(0xc00044e460)
        /usr/lib/go-1.11/src/net/http/server.go:1774 +0xd0
panic(0x893840, 0xcd3530)
        /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
main.handler(0x9a7620, 0xc0004568c0, 0xc0004bc800)
        /home/users/redacted/alertmanager_matrix/alertmanager_matrix.go:17 +0x39
net/http.HandlerFunc.ServeHTTP(0x944c78, 0x9a7620, 0xc0004568c0, 0xc0004bc800)
        /usr/lib/go-1.11/src/net/http/server.go:1993 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001e40c0, 0x9a7620, 0xc0004568c0, 0xc0004bc600)
        /home/users/redacted/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd0
net/http.serverHandler.ServeHTTP(0xc0001961a0, 0x9a7620, 0xc0004568c0, 0xc0004bc600)
        /usr/lib/go-1.11/src/net/http/server.go:2770 +0xab
net/http.(*conn).serve(0xc00044e460, 0x9a7de0, 0xc00015e400)
        /usr/lib/go-1.11/src/net/http/server.go:1876 +0x646
created by net/http.(*Server).Serve
        /usr/lib/go-1.11/src/net/http/server.go:2880 +0x2f5
2021/07/29 16:40:12 http: panic serving [::1]:44908: runtime error: invalid memory address or nil pointer dereference
goroutine 559 [running]:
net/http.(*conn).serve.func1(0xc00044e6e0)
        /usr/lib/go-1.11/src/net/http/server.go:1774 +0xd0
panic(0x893840, 0xcd3530)
        /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
main.handler(0x9a7620, 0xc0004a8380, 0xc000336600)
        /home/users/redacted/alertmanager_matrix/alertmanager_matrix.go:17 +0x39
net/http.HandlerFunc.ServeHTTP(0x944c78, 0x9a7620, 0xc0004a8380, 0xc000336600)
        /usr/lib/go-1.11/src/net/http/server.go:1993 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001e40c0, 0x9a7620, 0xc0004a8380, 0xc0004bca00)
        /home/users/redacted/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd0
net/http.serverHandler.ServeHTTP(0xc0001961a0, 0x9a7620, 0xc0004a8380, 0xc0004bca00)
        /usr/lib/go-1.11/src/net/http/server.go:2770 +0xab
net/http.(*conn).serve(0xc00044e6e0, 0x9a7de0, 0xc00015ea80)
        /usr/lib/go-1.11/src/net/http/server.go:1876 +0x646
created by net/http.(*Server).Serve
        /usr/lib/go-1.11/src/net/http/server.go:2880 +0x2f5
```

This also occurs whenever it receives an alert from alert manager.

Did you end up solving this in the end?

**Comment by ajs124** [comment]
I ended up solving this by deploying go-neb.
